baseURL = "https://javiercaram.github.io/uno/"
languageCode = "es"
title = "Mi Nuevo Sitio"
theme = "PaperMod"
defaultContentLanguage = "es"
enableRobotsTXT = true

[params]
    defaultTheme = "auto" # Puede ser "light", "dark" o "auto"
    ShowShareButtons = true
    ShowReadingTime = true
    ShowPostNavLinks = true

[languages]
  [languages.es]
    weight = 1
    languageName = "Español"
    contentDir = "content/es"
    [languages.es.menu]
        [[languages.es.menu.main]]
            identifier = "archives"
            name = "Archivos"
            url = "/archives/"
            weight = 10
        [[languages.es.menu.main]]
            identifier = "search"
            name = "Buscar"
            url = "/search/"
            weight = 20

   